### PR TITLE
Documentation with sphinx and readthedocs.org

### PR DESCRIPTION
**Pull request by pfackeldey**
This is a template for a readthedocs.io website! 
You can test it locally by installing `sphinx`via pip and then do from the `docs` directory:  
* `python -m sphinx "source" "build"`  
or  
* `make html`  
Now you can open the html in your browser with:  
* `open build/index.html`  

The input of the website is configured in the .rst files. They can be written manually or automatically with the `sphinx-apidoc` command. More info here: http://www.patricksoftwareblog.com/python-documentation-using-sphinx/  
As soon as you want we can merge it and everybody contributes to it. This is the easiest way I would suggest. Once there is a documentation we can use `readthedocs` (https://readthedocs.org/) to host it. It also provides a webhook which allows to build the documentation after every commit.  

Let me know what you think about this :)

### CODE REVIEW

**Comment by pfackeldey** [comment]
some updates:
to install on lx3b do:  
* `export PYTHONPATH=$HOME/.local/lib/python2.7/site-packages:$PYTHONPATH`  
* `pip install sphinx --user --upgrade`  
* `export PATH="$PATH:~/.local/bin/"`  

then you can use the sphinx executables!  
Here is a small appetizer...:  
[build_copy.tar.gz](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/files/1689149/build_copy.tar.gz)  

(Just download, unpack and run `firefox build_copy/html/index.html`)

**Comment by pfackeldey** [comment]
I think I can close this one now, since we use doxygen, right? :)

**Comment by greyxray** [comment]
I would say yes. I am pro doxygen just because it's simpler to maintain and I saw it being used way more often so it already showed its reliability once is set up. also people know how to use it

**Comment by pfackeldey** [comment]
ok thanks for your replies!

**Pull request closed without merging**
