### PR TITLE
cleaning of filelists incompatible with recent Kappa version

### PR DESCRIPTION
**Pull request by rfriese**
Dear all,
I cleaned the filelists a lot more and would like to hear your feedback first before I merge this into the master.

I removed those sample lists that do not work with the current master of the Kappa/Artus/KITHiggs Repository. One would have to jump back in git anyway to be able to run on them or could re-skim them. In Case of 8TeV this should be possible still since we keep Kappa Backward-compatible to CMSSW_5_3_X. For Spring15 we will never run on them ever again.

Additionaly, I removed the NAF and XROOTD filelists. It seemed to me that they have not been maintained in the last months and I do not see a need for them since DCAP is reliable and works site-independent.

Do you agree with these changes? There's no urgent need for cleaning them, but atm I can't realy see a reason for keeping them also.

Cheers

### CODE REVIEW

**Comment by thomas-mueller** [comment]
One quick comment: The creation of NAF* filelists was disabled in [this commit](https://github.com/artus-analysis/Artus/commit/5810dfac4e194ec8978c2ab280c41df6e739158c). I am not so sure, if the NAF* (in contrast to the less reliable XROOT*) filelists are really "deprecated". I think there are cases where they allow a much faster access to the files. The also ease copying single files for testing purposes somewhere else, because one can simply look up the full paths there.

Another point: cleaning up is always good! I agree, that we can delete all filelists **and the files on dCache**, that we anyhow cannot process with the current code. But I wont't be able to check this PR in detail. (Again here: constant nicks would make life easier, as only the files of superceeded dates would have to be deleted.)

**Comment by pistone87** [comment]
Hi Raphael,

I would like to keep the 8TeV samples, since I might need them again.
For running on them I still have a very old version of Kappa&Co. locally,
so the filelists in the new version of Kappa&Co. can be deleted
(I have the filelists that I need in my old working directory).

The important point is that the _files_ are not deleted. ;)

Thanks.

Cheers,
Claudia

**Comment by rfriese** [comment]
Spring15 and 8TeV samples had what you call "constant nicknames" :)

I for sure won't delete anything from someone else' dCache folder, even if that might be technically possible and Thomas put it in bold letters. 

with 

gfal-rm srm://dcache-se-cms.desy.de:8443/srm/managerv2?SFN=/pnfs/desy.de/cms/tier2/store/user/... -R

You can now recursively delete folders.

I checked running with Run2Analysis on 1000 events, which is the usual test job size. When reading the file from dcap it took 24s, from /pnfs/ 25s. Even if one might want to step back not using dcap the /pnfs/ paths can be extracted easily.

**Comment by rfriese** [comment]
I just checked the concern with copying files locally. You can use

gfal-copy dcap://dcache-cms-dcap.desy.de//pnfs/... file:////nfs/...

good thing about that: it works globally no matter where on earth you are

**Pull request merged**
