### PR TITLE
Moved Rochester Muon Corrections to Artus

### PR DESCRIPTION
**Pull request by annafriedel**
Due to the movement of the HttMuonCorrectionsProducer to Artus some changes have to be done in this Repository as well. Please check if everything works as usual with this changes and the changes made in the Artus pull request. I hope it does, but since I'm not used to the Htt analysis I can't check it myself.

### CODE REVIEW

**Comment by anehrkor** [comment]
Hi Anna,

thanks for taking care of this! However, please do not completely remove the HttMuonCorrectionsProducer since it is needed for [this](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/d8af40204e602a0d5b2e83b9dc3a1053d4cdfce3/src/Producers/HttMuonCorrectionsProducer.cc#L82-L86) operation in some cases. So if you could, please only remove the stuff connected to the rochester corrections.

Best,
Alex

**Comment by thomas-mueller** [comment]
Hi Anna,

I checked your changes and can confirm, that we get the same result as before. So I will merge both pull request after Alex's question is answered.

I have just a very small comment regarding the class structure of the muon corrections: I am not completely sure, whether deriving a new class for every correction is the best way to do. It becomes problematic in case one wants to apply more than just one correction. In case this is needed, I propose to move the code from the `RochMuonCorrectionsProducer` into the `Produce` function of the upper class `MuonCorrectionsProducer` and switch it on/off as you do it know and as for example different IDs are switched on/off in the `ValidMuonsProducer`.

Cheers,
Thomas

**Comment by annafriedel** [comment]
Ok thank you for your suggestions and also thank you for testing, Thomas.
The only problem I see, when I move the Rochester corrections to the original MuonCorrectionsProducer and leave the shifting in the HttMuonCorrectionsProducer is that you overloaded the ID of the MuonCorrectionsProducer, so it won't be possible to get access to the Artus Producer with your Configs right now, if I understood your code correctly. So what do you suggest? I can add a new ID to the Htt producer, but then I don't know which producer I should add to the ArtusConfigs? Both?

Cheers,
Anna

**Comment by annafriedel** [comment]
Now I hope I did everything as suggested. Please check again if everything works as intended in Htt analysis.
One more Question: Is [this](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/src/Producers/HttMuonCorrectionsProducer.cc#L33-L36) still needed? I do not really understand what this is for.

Cheers,
Anna

**Comment by anehrkor** [comment]
Hi Anna,

after removing a few inclusions of header files that no longer exist, everything seems to be working. Both rochester corrections and the energy scale shift show reasonable/expected results.

So I think we can merge this PR and the one in Artus. Thanks for your help with the changes in this repository! :)

Cheers,
Alex

**Pull request merged**
