### PR TITLE
Update to CMSSW 8_1_0

### PR DESCRIPTION
**Pull request by dwolfschlaeger**
-------- Update of our Framework for usage of CMSSW 8_1_0 ------------
-CMSSW 8_1_0 comes with a newer version of ROOT and a newer version of combine. 
-Tauspinner is no longer supported in CMSSW 8.
-datacard scripts updated with the latest combine syntaxes and methods (still some WIP).

Please, checkout our framework with the now updated checkout_packages script and let me know when some parts of your analyses do not work as before.

### CODE REVIEW

**Comment by pfackeldey** [comment]
You can source tauola and/or tauola++ with the help of cvmfs. In the CMS experiment repository you can choose your preferred architecture. Then you can source in `.../external/...` the tauola version. so in the end you can get tauola with something similar to:
`source /cvmfs/cms.cern.ch/slc6_amd64_gcc480/external/tauola/...`

**Comment by thomas-mueller** [comment]
We need version 1.1.5. of Tauola, which are available in `/cvmfs/sft.cern.ch/lcg/external/MCGenerators*/tauola++/1.1.5`. Other (manual) instructions are found in https://github.com/TauPolSoftware/TauolaSetup/blob/master/todo.pl.

**Comment by dwolfschlaeger** [comment]
I included tauspinner in our framework again and it seems to work. Scram compiles without complains and Artus runs as expected. Nevertheless, someone might validate the correct behaviour of tauspinner.

**Comment by pfackeldey** [comment]
It would be actual kind of nice (as a first sign of success), when travis-ci would be configured such, that it now builds CMSSW_810 and not CMSSW_747 anymore. By that you can already show that everything is compiling correctly.
Currently you can see that the continuous integration fails while building CMSSW 747. Just klick on "Details" and take a look at the job log.  
Easiest way to switch:  
You can probably do this by setting "env" option in the travis.yml:
```yml
env:
  - TEST_CMSSW_VERSION=CMSSW_8_0_28_patch1 SCRAM_ARCH=slc6_amd64_gcc530
```
and then change the script to:
```yml
script:
 - docker run --privileged  -e TEST_CMSSW_VERSION=${TEST_CMSSW_VERSION}
                            -e SCRAM_ARCH=${SCRAM_ARCH}
                            -v ${TRAVIS_BUILD_DIR}:/home/travis
                            -v '/home/short:/home/short' claria/cvmfs-cms /bin/bash 
                            -c "cd /home/; source /home/travis/test_build.sh"
```
This should do the trick. Maybe you still need to to some changes here then: https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/master/test_build.sh.

**Comment by pfackeldey** [comment]
hm... it is still building CMSSW 747. So I guess there are still changes needed in the `test_build.sh` script

**Comment by thomas-mueller** [comment]
I propose to have only one checkout script for the version, that is "officially" maintained. If you modify `checkout_packages.sh` such that it uses the newer CMSSW version, travis should pick this up automatically. Hoever, I expect travis problems due to MELA, where I still do not know how to solve them.

**Comment by dwolfschlaeger** [comment]
Btw: The second test tried to build for CMSSW810 but terminated due to an error in MELA.

**Comment by thomas-mueller** [comment]
Thanks, Dominik, for this work. I checked it and it seems to work fine. I will cross check the TauSpinner version once more with Vladimir.

Since now, CMSSW 810 is the "officially" supported version for our analysis. Please check out this new version and make sure you do not loose local changes in your old setup. You may copy the repositories with changes to the new setup to keep these changes.

**Comment by dwolfschlaeger** [comment]
Thanks for merging, Thomas. 
If you discover unexpected behavior related to this merge, please let me know. I'd be happy to help you fixing it. 

Best
Dominik

**Pull request merged**
